### ISSUE TITLE
Font size dropdown vs SILE code

### ISSUE THREAD

**Issue by aaronbell** [simoncozens/GlyphSILE#11]
I'm experimenting with the SILE preview window for rendering Lushootseed, and noticed something strange. When I enter normal text and click "Draw", everything renders at the point size determined in the drop down. However, if I use a SILE code command to set the font size (\font[size=30pt]), when I click draw the text is rendered at the text size stated in the code, but the space character is rendered at the text size stated in the "Font Size" dropdown! I got confused when the space seemed to totally disappear!

It would be good to resolve this issue, but might also be worth considering a WYSIWYG mode and a code mode to avoid potential conflicts between code entered in the panel and the other controls.

**Comment by simoncozens** [comment]
OK, this is an odd one, and I can't replicate it either: 
![screen shot 2015-11-24 at 21 59 24](https://cloud.githubusercontent.com/assets/106728/11367384/a9a84a8e-92f6-11e5-905c-ad2f37218d5f.png)

Just to check: are you rendering an instance or a master? And can you pop up the Lua console window and tell me if that says anything? (you may need to compile a dummy program like `print(1)` to flush the console buffer.)

**Comment by aaronbell** [comment]
Hmm. I'm getting it intermittently now. Was rendering an instance. Let me see if I can figure out how to replicate it more consistently. 

Another question, though:I'm finding that I can't use the 'features=' command with more than one opentype feature as indicated in the SILE manual. Following this format:

\font[features="+dlig,+hlig"]... % turn on discretionary and historic ligatures

I get this:
<img width="572" alt="screen shot 2015-11-24 at 9 20 32 am" src="https://cloud.githubusercontent.com/assets/8460297/11374778/a73beb44-928c-11e5-8d64-328e53458baa.png">

I've found replacing the comma after '90pt' with a semicolon seems to help, but the features section still fails. Any ideas?

**Comment by simoncozens** [comment]
Your quotes are curly. They should be straight: `features="+calt,+ccmp"`

**Comment by aaronbell** [comment]
The preview window in Glyphs seems to autocorrect them to curly when typing. Is
that a thing that can be turned off?

On Tue, Nov 24, 2015 at 12:00, simoncozens/GlyphSILE
reply@reply.github.com
wrote:
Your quotes are curly. They should be straight: features="+calt,+ccmp"

—
Reply to this email directly or view it on GitHub
[https://github.com/simoncozens/GlyphSILE/issues/11#issuecomment-159388579] .[https://github.com/notifications/beacon/AIEYCSvncv3Z3XUL-hHs84bi5Jek8hugks5pJLlGgaJpZM4GoQf9.gif]

**Comment by simoncozens** [comment]
Please try beta-2 from here: https://github.com/simoncozens/GlyphSILE/releases/download/beta-2/GlyphSILE-beta-2.zip

**Comment by aaronbell** [comment]
Just installed this and am still seeing the smart quotes :(

<img width="265" alt="screen shot 2015-12-01 at 11 07 18" src="https://cloud.githubusercontent.com/assets/8460297/11511060/b839e3d0-981b-11e5-955c-53c1e97e5026.png">

**Comment by simoncozens** [comment]
I think I've got it this time. Please delete your plugin, download the _new_ beta 2 (same file name, different content) and try again.

**Comment by aaronbell** [comment]
Looks good! Cheers.
