### ISSUE TITLE
beta-2 interacts badly with the export dialog

### ISSUE THREAD

**Issue by n7s** [simoncozens/GlyphSILE#12]
On Glyphs 2.2.2 (build 826 and 827) having the beta-2 plugin installed seems to somehow block the export dialog (File -> Export) from appearing. Kinda difficult to produce fonts that way :-)  Deleting the .glyphsPlugin file from the Plugins/ folder restores access to the export dialog. 

Attached is a console output of the error trace when the plugin is installed (along with the output of the defaults command for the app). The Glyphs developers have received the trace as well but couldn't reproduce the issue. The behaviour has been observed on Yosemite (and on El Capitan on a fresh install) with only that .glyphsPlugin file added or removed: same behaviour, so I'm guessing it might have something to do with GlyphSILE. 

[glyphs.app-log-output.txt](https://github.com/simoncozens/GlyphSILE/files/81984/glyphs.app-log-output.txt)

Hope this helps.
Thanks for your amazingly useful work on this.

**Comment by simoncozens** [comment]
Oh boy; I can't reproduce this on 827 / El Capitan. :( But it does sound a lot like a GlyphSILE bug. Do you mind helping me to debug it? Please try removing GlyphSILE and instead installing this deliberately broken version:

http://dealer.simon-cozens.org/~simon/tmp/GlyphSILE-stupid.zip

If that works (as in, the SILE part won't work, but you should at least be able to export fonts again) but beta-2 doesn't, then I will have narrowed down the problem to the most suspicious two lines of code.

**Comment by n7s** [comment]
Sorry, looks like installing this test plugin still blocks the Export dialog. Removing it restores access. The console log output is attached.  Is there a better way for me to prepare a trace for you? 
[glyphs.app-log-output-with-GlyphSILE-stupid.txt](https://github.com/simoncozens/GlyphSILE/files/83325/glyphs.app-log-output-with-GlyphSILE-stupid.txt)

**Comment by simoncozens** [comment]
OK. Try this: http://dealer.simon-cozens.org/~simon/tmp/GlyphSILE-even-stupider.zip

This contains GlyphSILE but on initialization does absolutely nothing. If you still can't export, it's not a GlyphSILE bug (even though it really looks like one). If you can export after that, here is a version which will count from 1 to 13 in the logs, like this:

```
GlyphSILE: 1
GlyphSILE: 2
GlyphSILE: 3
GlyphSILE: 4
...
```

Please let me know what number it gets up to: http://dealer.simon-cozens.org/~simon/tmp/GlyphSILE-instrumented.zip

**Comment by n7s** [comment]
OK. -even-stupider now brings the export dialog back.
-instrumented gets up to 10. Attached is the full log. 
[glyphs.app-log-output-GlyphSILE-instrumented.txt](https://github.com/simoncozens/GlyphSILE/files/83781/glyphs.app-log-output-GlyphSILE-instrumented.txt)

Thanks!

**Comment by simoncozens** [comment]
I think I see the problem, but this is code that @schriftgestalt contributed and I don't really understand. ;-)

The error is `[JSTTextView replaceCharactersInRange:withString:]: nil NSString given.` One piece of code says:

```
    NSString *Code = [[NSUserDefaults standardUserDefaults] objectForKey:@"LuaConsoleCode"];
    [_incomingCode setString:Code];
```

and another says:

```
    NSString *code = [[NSUserDefaults standardUserDefaults] objectForKey:@"SILE_Code"];
    if ([code length] > 0) {
        [_SILEInput setString:code];
    }
```

That looks to me like the first piece of code needs a guard around the string too.

@n7s, please try: http://dealer.simon-cozens.org/~simon/tmp/GlyphSILE-guarded.zip

**Comment by schriftgestalt** [comment]
The actual problem is the in line 5 of the log file. @n7s can you send the crash report that comes up when the app restarts? That will give me a bit more details. Or tell me exactly what version you have?

**Comment by n7s** [comment]
-guarded gets all the way to 13:

2016-01-10 17:54:12.795 Glyphs[8646:82630] JSTalk listening on port com.GeorgSeifert.Glyphs2.JSTalk
2016-01-10 17:54:17.426 Glyphs[8646:82630] GlyphSILE: 1
2016-01-10 17:54:17.432 Glyphs[8646:82630] GlyphSILE: 2
2016-01-10 17:54:17.440 Glyphs[8646:82630] GlyphSILE: 3
2016-01-10 17:54:17.440 Glyphs[8646:82630] GlyphSILE: 4
2016-01-10 17:54:17.441 Glyphs[8646:82630] GlyphSILE: 5
2016-01-10 17:54:17.441 Glyphs[8646:82630] GlyphSILE: 6
2016-01-10 17:54:17.444 Glyphs[8646:82630] GlyphSILE: 7
2016-01-10 17:54:17.663 Glyphs[8646:82630] GlyphSILE: 8
2016-01-10 17:54:17.663 Glyphs[8646:82630] GlyphSILE: 9
2016-01-10 17:54:17.663 Glyphs[8646:82630] GlyphSILE: 10
2016-01-10 17:54:17.663 Glyphs[8646:82630] GlyphSILE: 11
2016-01-10 17:54:17.664 Glyphs[8646:82630] GlyphSILE: 12
2016-01-10 17:54:17.665 Glyphs[8646:82630] GlyphSILE: 13
2016-01-10 17:54:25.625 Glyphs[8646:82632] removeTableForKey: 'VORG' table not found

**Comment by n7s** [comment]
This is on version 2.2.2 (827) on a test laptop running on a fresh 10.11.2 El Capitan. I didn't get the crash report dialog for this, I got the traces posted above as stderr by launching the app from the console.  

Thanks.

**Comment by n7s** [comment]
The error is gone with Glyphs 2.3b (839) with both beta-2 and -guarded. Thanks.
